<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mrole extends CI_Model
{

    public $table = 'ms_role';
    public $id = 'id_inc';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_inc,nama_role');
        $this->datatables->from('ms_role');
        //add this line for join
        //$this->datatables->join('table2', 'ms_role.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('role/setting/$1'),'<i class="fa fa-binoculars"></i>')." ".anchor(site_url('role/update/$1'),'<i class="fa fa-edit"></i>')."  ".anchor(site_url('role/delete/$1'),'<i class="fa fa-trash"></i>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_inc');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_inc', $q);
	$this->db->or_like('nama_role', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_inc', $q);
	$this->db->or_like('nama_role', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getMenu($id){
        $cm=$this->db->query('SELECT id_inc FROM ms_menu')->result_array();
        foreach($cm as $rm){
            $kode_menu=$rm['id_inc'];
            $sql="SELECT ms_menu_id FROM ms_privilege WHERE ms_role_id='$id' AND ms_menu_id='$kode_menu'";
            $qcm=$this->db->query($sql)->num_rows();
            if($qcm == null){
                $data=array('ms_menu_id'=>$kode_menu,'ms_role_id'=>$id);

                $this->db->insert('ms_privilege',$data);
            }
        }

        $qr=$this->db->query("SELECT * FROM (
                                SELECT b.id_inc kode_role,nama_menu,CASE parent WHEN 0 THEN '#'  ELSE NULL END AS parent,STATUS,a.sort sort
                                FROM ms_menu a , ms_privilege b WHERE a.id_inc=b.ms_menu_id 
                                AND parent=0 AND ms_role_id='$id' 
                                UNION 
                                    SELECT c.id_inc kode_role,a.nama_menu,b.nama_menu parent,STATUS,a.sort 
                                    FROM ms_menu a,(SELECT id_inc,nama_menu FROM ms_menu) b, ms_privilege c WHERE a.parent=b.id_inc AND a.id_inc=c.ms_menu_id AND ms_role_id='$id' ) cb ORDER BY parent ASC,cb.sort ASC")->result_array();
        return $qr;     
    }

    function do_role($kode_group,$role){
        $ua=$this->db->query("UPDATE ms_privilege SET status='0' WHERE ms_role_id ='$kode_group'");
        if($ua){
            $jumlah=count($role);
            for($i=0; $i < $jumlah; $i++){
                $kode_role=$role[$i];
                $ur=$this->db->query("UPDATE ms_privilege SET status='1' WHERE id_inc='$kode_role'");
                // echo "UPDATE ms_privilege SET status='1' WHERE id_inc='$kode_role'";
                // echo "<br>";
            }
        }

        return $ur;
    }

}

/* End of file Mrole.php */
/* Location: ./application/models/Mrole.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-04 04:25:57 */
/* http://harviacode.com */